# Generated by Django 4.1.2 on 2022-10-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_contactmessage_me_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='fakeortrue',
            field=models.CharField(max_length=200),
        ),
    ]
