# Generated by Django 4.1.2 on 2022-11-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_addnew_delete_addnews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnew',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
