# Generated by Django 4.1.3 on 2022-11-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0008_rename_contactme_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addnew",
            name="tag",
            field=models.CharField(
                choices=[
                    ("covid-19", "โควิด-19"),
                    ("hemp", "กัญชา"),
                    ("bank", "ธนาคาร"),
                ],
                default="covid-19",
                max_length=50,
            ),
        ),
    ]
