# Generated by Django 4.1.3 on 2022-12-15 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0009_alter_addnew_tag"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AddNew",
            new_name="New",
        ),
    ]
