# Generated by Django 4.1.4 on 2022-12-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0011_feedbacks_delete_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("fakeortrue", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=500)),
                ("detail", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Feedbacks",
        ),
    ]
