# Generated by Django 4.1.4 on 2022-12-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0013_alter_feedback_detail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedbacks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("fakeortrue", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=500)),
                ("text", models.TextField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
