# Generated by Django 4.1.4 on 2023-01-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0014_feedbacks_delete_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Csv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("text", models.CharField(max_length=500)),
                ("label", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
            ],
        ),
    ]
